version: '3.10'

services:

  'film-session':
    image: 'film-session'
    build: 
      context: ./film_session
      cache_to:
        - type=local,dest=data/cache
    depends_on:
      'film-session-db':
        condition: service_healthy
    ports:
      - 8080:8080
  
  'film-session-db':
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: '5s'
      start_period: '5s'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123

  'client':
    image: 'client'
    build: 
      context: ./client
      cache_to:
        - type=local,dest=data/cache
    depends_on:
      'client-db':
        condition: service_healthy
    ports:
      - 8081:8080
  
  'client-db':
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: '5s'
      start_period: '5s'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123